creates scripts to pull .vtt files from the gcp bucket instead of Amara
scimusmn/tsck-bionic-eyes-quiz-show pull request #24
Opened 2021-12-09 20:15 UTC by calym

The pipedream workflows are configured to save .vtt files to the storage bucket. These scripts provide the option to pull vtt files from a storage bucket to the local dev environment instead of directly from Amara. This can be used as a workaround for default record limits/paginated requests, or just as an alternate way of accessing caption files.

2021-12-09 20:45 UTC, tnordberg requested changes
Cool! I like that we have both these options now. 

I tested by deleting all the caption files, then using the scripts to refill my `captions` folder. It worked like a charm for the most part, but I had slightly different results with each script:

After running `save-captions`, a small group of files were not recreated:

https://d.pr/i/CT7WvI

@calym I think this might be correct as these files were consolidated to a single `quizintro` and `finalscore` captions. If that's right, we should delete them from the repo. Could you confirm?

After running `save-bucket-captions`, some test files were added, and I strangely did not recreate the `s1_i1_audio_en.vtt` caption:

https://d.pr/i/ZAJBtX

Also - I did have to fix a typo in the `package.json` script to point to the correct file (see line comment).

2021-12-09 20:45 UTC, tnordberg commented on package.json
> +    "save-bucket-captions": "node scripts/save-bucket-captoions.js",
Filename typo: `save-bucket-captoions.js` -> `save-bucket-captions.js`

2021-12-09 21:28 UTC, calym commented on package.json
> +    "save-bucket-captions": "node scripts/save-bucket-captoions.js",
You're more familiar with the files this project needs, but yes, that sounds correct from what I know about the intro files. The new script pulls all .vtt files from the bucket and doesn't/can't filter by project name the way the Amara requests do, so it makes more sense that some redundant or test files might show up. Good thing to keep in mind if we're evaluating use cases.

2021-12-10 15:43 UTC, tnordberg commented on package.json
> +    "save-bucket-captions": "node scripts/save-bucket-captoions.js",
@calym I checked the Drive and yes, those captions are no longer needed (https://d.pr/i/CT7WvI). I'll remember to ask the contractor to fill in the missing caption paths as part of the next milestone.

2021-12-13 17:33 UTC, merged